In [7]:
# <- this is the symbol for a comment

# Things we'll be covering:
# - Creating and printing variables
# - Conditionals and loops
# - Lists
# - NumPy and Documentation

Hello!

# asdf

In [8]:
# Creating a variable
# Note - do not need to indicate type
n = 4
lecture = 'INFO 1998'

# if you want to print it
print(n)
print(lecture)

# can also just type the variable name without 'print' (as long as the last item in cell)
lecture

4
INFO 1998


'INFO 1998'

In [9]:
total = 0
for x in range(1, n+1): # note that range is exclusive for the right value
    print(x)
    total += x
print("sum", total)

# One-line solution (bonus)
# print(sum([x for x in range(1, n+1)]))

1
2
3
4
sum 10


In [10]:
# if statement
if total == 10:
    print ("sum is 10!!!")
else:
    print ("sum is not 10")

sum is 10!!!


In [11]:
# lets talk about lists
list1 = [3,1,4,1,5,9,2,6]

In [12]:
print('fifth index', list1[5])

print("4 Through 7", list1[4:8]) # exclusive end index

print("Before", list1)

list1.append(5)

print("After", list1)

fifth index 9
4 Through 7 [5, 9, 2, 6]
Before [3, 1, 4, 1, 5, 9, 2, 6]
After [3, 1, 4, 1, 5, 9, 2, 6, 5]


In [13]:
total = 0
for x in list1:
    print(x)
    total += x
print("sum", total)

# print(sum(list1))

3
1
4
1
5
9
2
6
5
sum 36


In [14]:
# You can perform different operations on each value in a list
# + - * / ** %

In [15]:
# you can change the values of elements in arrays
for i in range(len(list1)):
  list1[i] += 1
list1

[4, 2, 5, 2, 6, 10, 3, 7, 6]

In [16]:
# be careful! this loop changes only the loop variable, not the list contents
for i in list1:
  i += 1
list1

[4, 2, 5, 2, 6, 10, 3, 7, 6]

In [17]:
# Importing Numpy
# fundamental package for computing
import numpy as np

In [18]:
arr1 = np.array([1,2,3])
print (arr1)

[1 2 3]


In [19]:
lst = [1,3]
np.array(lst)
arr2 = np.array([[4,5,6],[7,8,9]]) #2d array
print (arr2)

[[4 5 6]
 [7 8 9]]


In [20]:
print ("first index is first row: ", arr2[0]) # note that we start with 0

print ("specific entry: ", arr2[1][2])

first index is first row:  [4 5 6]
specific entry:  9


In [21]:
# can create an array filled with random values
arr3 = np.random.randint(1, 10,(2,3)) #(low,high-exclusive,(#rows,#cols))
print(arr3)

[[9 9 7]
 [6 4 5]]


In [22]:
# can perform fun operations
np.median(arr3[0])
np.max(arr3)
np.sum(arr3[1])

np.int64(15)

In [23]:
print(arr1)
print(arr2)

[1 2 3]
[[4 5 6]
 [7 8 9]]


In [24]:
np.union1d(arr1,arr2) # will not contain duplicate values

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr4 = np.array([5,6,7])
print(np.intersect1d(arr2, arr4))

[5 6 7]


In [26]:
# more examples and commands in the homework!!!