# Introduction: Fundamentals of Python and Numpy

Lecture 1 | February 12, 2020

<b>NetID</b>: PLEASE FILL ME OUT!

___

## The Basics

In [1]:
# This is a comment

In [2]:
# Creating Variables
var1 = 'Hello World'

In [3]:
# You can print in Jupyter Notebooks without a print statement.
var1

'Hello World'

In [4]:
# Or with one if it is not the last line
print(var1)

Hello World


In [5]:
# Lets talk about lists
list1 = [0,1,2,3,4,5,6,7,8,9]

In [6]:
print('fifth index', list1[5])

print("4 Through 7", list1[4:8])

print("Before", list1)

list1.append(10)

print("After", list1)

fifth index 5
4 Through 7 [4, 5, 6, 7]
Before [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
After [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [7]:
# for loops and if statments are made very easy in python, just follow this example
newArray = [1,2,3,4,5,6,7,8,9]
for x in newArray:
    if x%2 == 0:
        print(x,'is even')
    else:
        print(x,'is odd')

1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd


In [8]:
# list comprehention is a little more difficult and isn't necessary, but if you know how to do it, it saves time
allEven = [x for x in range(0,100) if x%2==0]
print(allEven)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


____

## Example 1: Put all the multiples of 15 from 1 to 1000 in a list (Save it as a variable called 'multiples_15'): 

In [10]:
multiples_15 = []
for num in range(1, 1000):
    if num % 15 == 0:
        multiples_15.append(num)
        
print(multiples_15)

[15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360, 375, 390, 405, 420, 435, 450, 465, 480, 495, 510, 525, 540, 555, 570, 585, 600, 615, 630, 645, 660, 675, 690, 705, 720, 735, 750, 765, 780, 795, 810, 825, 840, 855, 870, 885, 900, 915, 930, 945, 960, 975, 990]


___

## Introduction to Numpy

In [11]:
# Importing Numpy
import numpy as np

In [12]:
arr1 = np.array([1,2,3]) #seperate with commas

In [13]:
print(arr1)

[1 2 3]


In [14]:
arr2 = np.array([[1,2,3],[4,5,6]]) #2d array

In [15]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [16]:
arr2.shape #get the shape of the array

(2, 3)

### Different Ways to Create numpy arrays

In the code below, we create a number of different sized arrays with different shapes and values.  Numpy has some built in methods (listed below) which help us quickly and easily create multidimensional arrays with pre-filled values.

**np.zeros((dimensions))** creates an array of zeros with the specified dimensions

**np.full((dimensions), value)** creates an array with the specified dimensions where every element is the specified value

**np.random.random(dimensions)** generates an array of random floating-point values between 0 and 1

In [17]:
# create a 3x4 array of zeros
ex1 = np.zeros((3, 4))      
print(ex1)    

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
# create a 2x3 array filled with 9.0
ex2 = np.full((2,3), 9.0)  
print(ex2)   

[[9. 9. 9.]
 [9. 9. 9.]]


In [19]:
# create a 2x3 array of random floating-point numbers between 0 and 1
ex3 = np.random.random((2,3))
print(ex3)    

[[0.79757188 0.55836614 0.97840796]
 [0.57138736 0.56690525 0.66490948]]


In [20]:
ex3[0] #this first index if the first row

array([0.79757188, 0.55836614, 0.97840796])

In [21]:
ex4 =  np.random.randint(1,10,(5,10)) #(low,high-exclusive,shape)
print(ex4)

[[4 9 3 1 7 6 1 5 9 1]
 [2 8 6 6 7 7 7 1 8 3]
 [7 8 5 7 5 5 2 2 3 4]
 [1 2 5 8 6 1 9 9 7 5]
 [2 9 7 1 7 5 1 4 5 9]]


In [22]:
ex4[2]

array([7, 8, 5, 7, 5, 5, 2, 2, 3, 4])

In [23]:
np.median(ex4[1])

6.5

___

### Mathematical Operations 

In [24]:
arr1 = np.array([2,4,6,8,10])

In [25]:
print(arr1)

[ 2  4  6  8 10]


In [26]:
print(np.sqrt(arr1))

[1.41421356 2.         2.44948974 2.82842712 3.16227766]


In [27]:
np.max(arr1)

10

In [28]:
np.min(arr1)

2

In [29]:
np.median(arr1)

6.0

In [30]:
np.std(arr1)

2.8284271247461903

In [31]:
arr1+1

array([ 3,  5,  7,  9, 11])

In [32]:
arr1*2

array([ 4,  8, 12, 16, 20])

In [33]:
print(arr1[2:])

[ 6  8 10]


In [34]:
np.unique(np.array([1,1,1,1,2]))

array([1, 2])

In [35]:
arr2 = np.array([3,6,9,12,15])

In [36]:
np.add(arr1,arr2)

array([ 5, 10, 15, 20, 25])

In [37]:
arr1+arr2

array([ 5, 10, 15, 20, 25])

In [38]:
arr1.dot(arr2)

330

In [39]:
np.sum(arr1)

30

___

## Example 2: Create an random integer array with a min of 1, max of 9 (inclusive), and shape of (20,10) so 20 rows and 10 columns. Then for each row, sum the random integers and add all the sums to a list called 'random_sums'. 

In [50]:
randArray = np.random.randint(1,10,(20,10))
print(randArray)
random_sums = []
for i in range(0,20):
    random_sums.append(np.sum(randArray[i]))
print(random_sums)

[[6 7 2 5 9 8 9 4 8 1]
 [6 4 9 2 8 6 8 4 9 5]
 [9 2 2 3 8 5 5 8 1 3]
 [7 6 7 8 6 7 9 6 1 8]
 [5 7 8 7 4 2 7 1 1 6]
 [7 5 3 2 9 1 1 7 3 4]
 [9 4 3 2 2 6 1 5 2 1]
 [2 8 3 7 4 1 9 2 8 8]
 [2 6 3 5 9 5 9 4 3 6]
 [3 9 9 7 8 3 6 8 3 7]
 [7 6 3 8 2 3 4 6 2 7]
 [5 9 4 2 2 3 9 4 6 8]
 [1 4 9 4 7 9 1 9 6 9]
 [1 1 3 3 9 9 6 6 1 9]
 [7 7 4 4 7 9 2 4 1 4]
 [6 8 6 6 6 1 3 9 7 9]
 [6 8 1 5 9 9 1 9 9 7]
 [3 7 1 3 9 5 4 1 4 1]
 [2 3 1 2 6 7 6 6 5 5]
 [8 8 9 6 2 7 2 8 2 3]]
[59, 61, 46, 65, 48, 42, 35, 52, 52, 63, 48, 52, 59, 48, 49, 61, 64, 38, 43, 55]


___

## Sets

In [42]:
arr1 = np.array([x for x in range(0,50) if x%5 > 2])
arr2 = np.array([x for x in range(0,50) if x%7 > 3])

print('array 1:', arr1)
print('array 2:', arr2)

array 1: [ 3  4  8  9 13 14 18 19 23 24 28 29 33 34 38 39 43 44 48 49]
array 2: [ 4  5  6 11 12 13 18 19 20 25 26 27 32 33 34 39 40 41 46 47 48]


In [43]:
union = np.union1d(arr1, arr2) #in either arr1 or arr2
print('union:', union)

union: [ 3  4  5  6  8  9 11 12 13 14 18 19 20 23 24 25 26 27 28 29 32 33 34 38
 39 40 41 43 44 46 47 48 49]


In [44]:
intersect = np.intersect1d(arr1, arr2) #in both arr1 and arr2
print('intersect:', intersect)

intersect: [ 4 13 18 19 33 34 39 48]


## Reshaping

In [45]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
arr1.reshape(2, -1) #first number is the number of rows, -1 automatically selects the number that works

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [47]:
np.transpose(arr1) #switches the axis

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

____

## Example 3: Find the numbers that are in both 'multiples_15' and 'random_sums' and put them in an array called 'both'.

In [49]:
both=intersect=np.intersect1d(multiples_15,random_sums) #in both arr1 and arr2
print(both)

[45]


____

<b>Final Note</b>: We know that you might not have any experience in Python or Computer Science/Math in general, and that's completely fine. Don't be intimidated - this is a part of the process! Please come to office hours, and one of the instructors would give you a crash course. Additionally, we plan to host a Python workshop soon so that you can bridge the gap, if any. If you still feel underprepared, please come talk to one of the instructors - we will work it out.