# Introduction: Fundamentals of Python and Numpy

Lecture 1 | September 23, 2020

<b>NetID</b>:

___

## The Basics
### This is text not code
This cell is a markdown cell

In [1]:
# This is a comment

In [2]:
# Creating Variables
var1 = 'Hello World'

In [3]:
# You can print in Jupyter Notebooks without a print statement.
var1

'Hello World'

In [4]:
# Or with one if it is not the last line
print(var1)

Hello World


In [5]:
# Lets talk about lists
list1 = [0,1,2,3,4,5,6,7,8,9]

In [6]:
print('fifth index', list1[5])

print("4 Through 7", list1[4:8])

print("Before", list1)

list1.append(10)

print("After", list1)

fifth index 5
4 Through 7 [4, 5, 6, 7]
Before [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
After [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [9]:
# for loops and if statments are made very easy in python, just follow this example
newArray = [1,2,3,4,5,6,7,8,9]
for x in newArray:
    if x%2 == 0:
        print(x,'is even')
    else:
        print(x,'is odd')

1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd


In [10]:
# list comprehention is a little more difficult and isn't necessary, but if you know how to do it, it saves time
allEven = [x for x in range(0,100) if x%2==0]
print(allEven)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


____

## Example 1: Put all the multiples of 15 from 1 to 1000 in a list (Save it as a variable called 'multiples_15'): 

In [ ]:
# The above examples should be helpful in solving this question! Ask a TA for help if you're stuck.

multiples_15 = []
# YOUR CODE HERE - The most common solution would have 3 lines!
        
print(multiples_15)

___

## Introduction to Numpy

In [16]:
# Importing Numpy
import numpy as np

In [17]:
arr1 = np.array([1,2,3]) #seperate with commas

In [18]:
print(arr1)

[1 2 3]


In [21]:
arr2 = np.array([[1,2,3],[4,5,6]]) #2d array

In [22]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [23]:
arr2.shape #get the shape of the array

(2, 3)

### Different Ways to Create numpy arrays

In the code below, we create a number of different sized arrays with different shapes and values.  Numpy has some built in methods (listed below) which help us quickly and easily create multidimensional arrays with pre-filled values.

**np.zeros((dimensions))** creates an array of zeros with the specified dimensions

**np.full((dimensions), value)** creates an array with the specified dimensions where every element is the specified value

**np.random.random(dimensions)** generates an array of random floating-point values between 0 and 1

In [24]:
# create a 3x4 array of zeros
ex1 = np.zeros((3, 4))      
print(ex1)    

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
# create a 2x3 array filled with 9.0
ex2 = np.full((2,3), 9.0)  
print(ex2)   

[[9. 9. 9.]
 [9. 9. 9.]]


In [27]:
# create a 2x3 array of random floating-point numbers between 0 and 1
ex3 = np.random.random((2,3))
print(ex3)    

[[0.79887141 0.08679967 0.11663571]
 [0.82783172 0.42535353 0.87298452]]


In [30]:
ex3[0] #this first index if the first row

array([0.79887141, 0.08679967, 0.11663571])

In [31]:
ex4 =  np.random.randint(1,10,(5,10)) #(low,high-exclusive,shape)
print(ex4)

[[9 3 8 7 8 4 8 3 8 2]
 [3 9 2 5 4 3 3 7 7 7]
 [3 4 1 2 6 5 9 6 6 1]
 [2 4 1 9 5 5 5 8 5 3]
 [5 3 6 1 3 2 9 2 3 5]]


In [32]:
ex4[2]

array([3, 4, 1, 2, 6, 5, 9, 6, 6, 1])

In [33]:
np.median(ex4[1])

4.5

___

### Mathematical Operations 

In [34]:
arr1 = np.array([2,4,6,8,10])

In [35]:
print(arr1)

[ 2  4  6  8 10]


In [36]:
print(np.sqrt(arr1))

[1.41421356 2.         2.44948974 2.82842712 3.16227766]


In [38]:
np.max(arr1)

10

In [39]:
np.min(arr1)

2

In [40]:
np.median(arr1)

6.0

In [41]:
np.std(arr1)

2.8284271247461903

In [42]:
arr1+1

array([ 3,  5,  7,  9, 11])

In [43]:
arr1*2

array([ 4,  8, 12, 16, 20])

In [44]:
print(arr1[2:])

[ 6  8 10]


In [45]:
np.unique(np.array([1,1,1,1,2]))

array([1, 2])

In [46]:
arr2 = np.array([3,6,9,12,15])

In [47]:
np.add(arr1,arr2)

array([ 5, 10, 15, 20, 25])

In [48]:
arr1+arr2

array([ 5, 10, 15, 20, 25])

In [49]:
arr1.dot(arr2)

330

In [50]:
np.sum(arr1)

30

___

## Example 2: Create an random integer array with a min of 1, max of 10, and shape of (20,10) so 20 rows and 8 columns. Then for each row, sum the random integers and add all the sums to a list called 'random_sums'. 

In [ ]:
randArray = # YOUR CODE HERE
random_sums = []
# YOUR CODE HERE
print(random_sums)

___

## Sets

In [ ]:
arr1 = np.array([x for x in range(0,50) if x%5 > 2])
arr2 = np.array([x for x in range(0,50) if x%7 > 3])

print('array 1:', arr1)
print('array 2:', arr2)

In [ ]:
union = np.union1d(arr1, arr2) #in either arr1 or arr2
print('union:', union)

In [ ]:
intersect = np.intersect1d(arr1, arr2) #in both arr1 and arr2
print('intersect:', intersect)

## Reshaping

In [ ]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1)

In [ ]:
arr1.reshape(2, -1) #first number is the number of rows, -1 automatically selects the number that works

In [ ]:
np.transpose(arr1) #switches the axis

____

## Example 3: Find the numbers that are in both 'multiples_15' and 'random_sums' and put them in an array called 'both'.

In [ ]:
# YOUR CODE HERE - The most common solution would have just 1 line!
print(both)

____

<b>Final Note</b>: We know that you might not have any experience in Python or Computer Science/Math in general, and that's completely fine. Don't be intimidated - this is a part of the process! Please come to office hours, and one of the instructors would give you a crash course. Additionally, we plan to host a Python workshop soon so that you can bridge the gap, if any. If you still feel underprepared, please come talk to one of the instructors - we will work it out.