## Python Basics
Basic Python data structures are lists which can act as arrays, stacks, queues; dictionaries which are hashtables; sets.
Python lists are very versatile as compared to Java lists as you can include values of different types in one list (same with dictionaries). 

In [8]:
lst = [0]*5
print(lst)
lst = []
lst = list(range(5))
print(lst[1:3])
lst = [1,(2,3),'a','b']
print(lst)
grades = [apples, oranges, bananas]
lst = [('Ben', 2), ('Emily', 5), ('Joe',6), ('Jerry', 3)]
summation = 0
for item in lst:
    summation += item[1]
apples = {'Ben': 2, 'Emily': 5, 'Joe': 6, 'Jerry': 3}
dictionary['Emily']
for key in dictionary.keys():
    summation += dictionary[key]
tup = ('Ben', 2)
tup[1] += 1
apples['Ben'] += 1

[0, 0, 0, 0, 0]
[1, 2]
[1, (2, 3), 'a', 'b']
1
(1, 2, 'a')


In [30]:
dictionary = {}
dictionary['a'] = 1
dictionary[1] = (2,3)
dictionary[2] = 'abc'
print(dictionary)
print(dictionary['a'])

{'a': 1, 1: (2, 3), 2: 'abc'}
1


In [31]:
setter = set()
setter.add(1)
setter.add(2)
print(setter)
setter.add(1)
print(setter)

{1, 2}
{1, 2}


Here are some basic functions and operations you can perform with lists (as well as general python syntax)

In [33]:
lst.append('hi')
print(lst)
lst.pop()
print(lst)
lst += '2'
print(lst)
for item in lst:
    print(item)
for item in range(len(lst)):
    if item%2 == 0:
        print(lst[item])
    elif item%3 == 0:
        print(lst[item])
    else:
        print("what's up")
        

[1, (2, 3), 'a', 'b', '2', 'hi']
[1, (2, 3), 'a', 'b', '2']
[1, (2, 3), 'a', 'b', '2', '2']
1
(2, 3)
a
b
2
2
1
what's up
a
b
2
what's up


# Numpy
Numpy is a package that contains many routines for fast matrix and vector operations. Behind the scenes, rather than executing slow Python code, numpy functions often execute code that is compiled and highly optimized (using C).

If you are not familiar with the Numpy package, you can read an overview of it <a href="https://docs.scipy.org/doc/numpy-dev/user/quickstart.html">here</a>, and find a full API <a href="https://docs.scipy.org/doc/numpy/reference/">here</a>. 
If you have anaconda already installed, this library should already be installed and you can import it directly. Otherwise you would normally do pip3 install 'library name'.

In [10]:
import numpy as np
X = np.array([[1,2,3], [4,5,6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

Unlike normal python lists, numpy arrays must contain a homogenous value set, meaning they can't have values of different types: 

In [11]:
Y = np.array([1,2,3], ['a', 'b', 'c'])

TypeError: Field elements must be 2- or 3-tuples, got ''a''

The first homework assignment already teaches a lot of functions that you'll need in this class and is a good reference for when you're doing future homework assignments. For this workshop I'll go over some functions not in the homework that are still useful and nice to know. (No need to memorize these things, you'll use them more and more and get the hang of the syntax and which functions are important to know).

In [13]:
v1=np.array([3,4,5])
print("This is a numpy vector:{}. It's shape is {}".format(v1, v1.shape))
v2=v1.reshape((3,1))
print("This is a column vector (matrix):\n{}. It's shape is {}".format(v2, v2.shape))
v3=v1.reshape((1,3))
print("This is a row vector (matrix):{}. It's shape is {}".format(v3,v3.shape))

This is a numpy vector:[3 4 5]. It's shape is (3,)
This is a column vector (matrix):
[[3]
 [4]
 [5]]. It's shape is (3, 1)
This is a row vector (matrix):[[3 4 5]]. It's shape is (1, 3)


In [42]:
v4=v2+v1
print("This is not what we want when we add v2 and v1: \n{}".format(v4))
v5 = v2.flatten() + v1 
print("This is what we want: {}".format(v5))

This is not what we want when we add v2 and v1: 
[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]
This is what we want: [ 6  8 10]


As you can see, numpy is actually pretty smart and in instances where matrix operations can't technically be done, it takes a smart guess as to what you want to do with the matrices. In the past example, you can't add a (3,1) matrix to a (1,3) matrix normally, but numpy guesses that you want to form a (3,3) matrix so it transforms both into (3,3) matrices and then adds them. Sometimes it's useful and sometimes it'll cause a bug if you don't know what you're really doing with the code. 

In [43]:
print("Dimensions of the matrix".format(v4.shape))
print("What Dimension matrix: {}".format(v4.ndim))
print("Number of elements: {}".format(v4.size))

(3, 3)
2
9


In [14]:
three_D = np.zeros((3, 4, 4))
print(three_D)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


The lecture covers dot products but what about element-wise multiplication and cross products?

In [56]:
arr1 = np.array([2,4,6,8,10])
arr2 = np.array([3,6,9,12,15])
X = np.array([[1,2], [3,4]])
Y = np.array([[4,5],[5,6]])
print("Element wise multiplication: {}".format(arr1*arr2))
print("Dot Product/Normal Matrix Multiplication: {}".format(np.dot(arr1, arr2)))
print(X)
print(Y)
print("Cross Product: {}".format(np.cross(X, Y)))

Element wise multiplication: [  6  24  54  96 150]
Dot Product/Normal Matrix Multiplication: 330
[[1 2]
 [3 4]]
[[4 5]
 [5 6]]
Cross Product: [-3 -2]


In [58]:
print("Some syntactic sugar: \n{}".format(X.T)

Some syntactic sugar: 
[[1 3]
 [2 4]]


## Additional Resources
If you want to learn Python for coding interviews, data structures, algorithms:

https://leetcode.com/

https://www.geeksforgeeks.org/

If you want to learn beginner Python:

Take CS 1110

or watch this https://www.youtube.com/watch?v=Z1Yd7upQsXY&list=PLBZBJbE_rGRWeh5mIBhD-hhDwSEDxogDg (basic python 
tutorial similar to this)

As for things data science and machine learning related, we'll give recommendations throughout the course for further self-study or hopefully give you the knowledge for googling (the best recommendation). If you want more, come to office hours and we can recommend more material. For now here's some stuff:

https://towardsdatascience.com/

https://www.kaggle.com/