In [1]:
# <- this is the symbol for a comment

# Things we'll be covering:
# - Creating and printing variables
# - Conditionals and loops
# - Lists
# - NumPy and Documentation

In [2]:
# Creating a variable
# Note - do not need to indicate type
n = 4
lecture = 'INFO 1998'

# if you want to print it
print(n)
print(lecture)

# can also just type the variable name without 'print' (as long as the last item in cell)
lecture

4
INFO 1998


'INFO 1998'

In [3]:
total = 0
for x in range(1, n+1): # note that range is exclusive for the right value
    print(x)
    total += x
print("sum", total)

# One-line solution (bonus)
# print(sum([x for x in range(1, n+1)]))

1
2
3
4
sum 10


In [5]:
# if statement
if total == 10:
    print ("sum is 10!!!")
else:
    print ("sum is not 10")

sum is 10!!!


In [6]:
# lets talk about lists
list1 = [3,1,4,1,5,9,2,6]

In [8]:
print('fifth index', list1[5])

print("4 Through 7", list1[4:8]) # exclusive end index

print("Before", list1)

list1.append(5)

print("After", list1)

fifth index 9
4 Through 7 [5, 9, 2, 6]
Before [3, 1, 4, 1, 5, 9, 2, 6, 5]
After [3, 1, 4, 1, 5, 9, 2, 6, 5, 5]


In [9]:
total = 0
for x in list1:
    print(x)
    total += x
print("sum", total)

# print(sum(list1))

3
1
4
1
5
9
2
6
5
5
sum 41


In [10]:
# You can perform different operations on each value in a list
# + - * / ** %

In [ ]:
# Importing Numpy
# fundamental package for computing
import numpy as np

In [ ]:
arr1 = np.array([1,2,3])
print (arr1)

[1 2 3]


In [ ]:
arr2 = np.array([[4,5,6],[7,8,9]]) #2d array
print (arr2)

[[4 5 6]
 [7 8 9]]


In [ ]:
print ("first index is first row: ", arr2[0]) # note that we start with 0

print ("specific entry: ", arr2[1][2])

first index is first row:  [1 2 3]
specific entry:  6


In [ ]:
# can create an array filled with random values
arr3 = np.random.randint(1, 10,(2,3)) #(low,high-exclusive,(#rows,#cols))
print(arr3)

[[1 7 5]
 [6 1 8]]


In [ ]:
# can perform fun operations
np.median(arr3[0])
np.max(arr3)
np.sum(arr3[1])

array([[2, 8, 6],
       [7, 2, 9]])

In [ ]:
print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
np.union1d(arr1,arr2) # will not contain duplicate values

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr4 = np.array([5,6,7])
print(np.intersect1d(arr2, arr4))

[5 6 7]


In [ ]:
# more examples and commands in the homework!!!