# Assignment 1: Fundamentals of Python and Numpy

### Net ID: PLEASE FILL ME OUT!

___

### Problems:

*   Problem 1 (3 points)
*   Problem 2 (4 points)
* Problem 3 (2 points)
* Problem 4 (1 point)



## Basics of Python

In [ ]:
# This is a comment

In [ ]:
# Creating Variables
var1 = 'Hello World'

In [ ]:
# You can print in Jupyter Notebooks without a print statement.
var1

'Hello World'

In [ ]:
# Or with one if it is not the last line
print(var1)

Hello World


In [ ]:
# Lets talk about lists
list1 = [0,1,2,3,4,5,6,7,8,9]

In [ ]:
print('fifth index', list1[5])

print("4 Through 7", list1[4:8])

print("Before", list1)

list1.append(10)

print("After", list1)

fifth index 5
4 Through 7 [4, 5, 6, 7]
Before [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
After [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
# for loops and if statments are made very easy in python, just follow this example
newArray = [1,2,3,4,5,6,7,8,9]
for x in newArray:
    if x%2 == 0:
        print(x,'is even')
    else:
        print(x,'is odd')

1 is odd
2 is even
3 is odd
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is odd


In [ ]:
# list comprehention is a little more difficult and isn't necessary, but if you know how to do it, it saves time
allEven = [x for x in range(0,100) if x%2==0]
print(allEven)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


____

## Problem 1: Put all the multiples of 15 from 1 to 1000 in a list (Save it as a variable called 'multiples_15') (3 pts):

In [ ]:
# The above examples should be helpful in solving this question! Ask a TA for help if you're stuck.

multiples_15 = []
# YOUR CODE HERE - There are many correct answers!


[0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360, 375, 390, 405, 420, 435, 450, 465, 480, 495, 510, 525, 540, 555, 570, 585, 600, 615, 630, 645, 660, 675, 690, 705, 720, 735, 750, 765, 780, 795, 810, 825, 840, 855, 870, 885, 900, 915, 930, 945, 960, 975, 990]


___

## Introduction to Numpy

In [ ]:
# Importing Numpy
import numpy as np

In [ ]:
arr1 = np.array([1,2,3]) #seperate with commas

In [ ]:
print(arr1)

[1 2 3]


In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]]) #2d array

In [ ]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2.shape #get the shape of the array

(2, 3)

### Different Ways to Create numpy arrays

In the code below, we create a number of different sized arrays with different shapes and values.  Numpy has some built in methods (listed below) which help us quickly and easily create multidimensional arrays with pre-filled values.

**np.zeros((dimensions))** creates an array of zeros with the specified dimensions

**np.full((dimensions), value)** creates an array with the specified dimensions where every element is the specified value

**np.random.random(dimensions)** generates an array of random floating-point values between 0 and 1

In [ ]:
# create a 3x4 array of zeros
ex1 = np.zeros((3, 4))
print(ex1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# create a 2x3 array filled with 9.0
ex2 = np.full((2,3), 9.0)
print(ex2)

[[9. 9. 9.]
 [9. 9. 9.]]


In [ ]:
# create a 2x3 array of random floating-point numbers between 0 and 1
ex3 = np.random.random((2,3))
print(ex3)

[[0.09530339 0.48913666 0.77673932]
 [0.42524033 0.0717148  0.15333945]]


In [ ]:
ex3[0] #this first index if the first row

array([0.09530339, 0.48913666, 0.77673932])

In [ ]:
ex4 =  np.random.randint(1,10,(5,10)) #(low,high-exclusive,shape)
print(ex4)

[[7 5 5 6 4 8 6 6 6 2]
 [2 1 2 8 3 9 6 5 1 1]
 [6 9 7 3 3 7 7 8 2 8]
 [5 1 3 7 6 3 7 9 6 6]
 [4 2 2 1 7 4 9 6 3 2]]


In [ ]:
ex4[2]

array([6, 9, 7, 3, 3, 7, 7, 8, 2, 8])

In [ ]:
np.median(ex4[1])

2.5

___

### Mathematical Operations

In [ ]:
arr1 = np.array([2,4,6,8,10])

In [ ]:
print(arr1)

[ 2  4  6  8 10]


In [ ]:
print(np.sqrt(arr1))

[1.41421356 2.         2.44948974 2.82842712 3.16227766]


In [ ]:
np.max(arr1)

10

In [ ]:
np.min(arr1)

2

In [ ]:
np.median(arr1)

6.0

In [ ]:
np.std(arr1)

2.8284271247461903

In [ ]:
arr1+1

array([ 3,  5,  7,  9, 11])

In [ ]:
arr1*2

array([ 4,  8, 12, 16, 20])

In [ ]:
print(arr1[2:])

[ 6  8 10]


In [ ]:
np.unique(np.array([1,1,1,1,2]))

array([1, 2])

In [ ]:
arr2 = np.array([3,6,9,12,15])

In [ ]:
np.add(arr1,arr2)

array([ 5, 10, 15, 20, 25])

In [ ]:
arr1+arr2

array([ 5, 10, 15, 20, 25])

In [ ]:
arr1.dot(arr2)

330

In [ ]:
np.sum(arr1)

30

___

## Problem 2: Create an random integer array with a min of 1, max of 9 (inclusive), and shape of (20,10) so 20 rows and 10 columns. Then for each row, sum the random integers and add all the sums to a list called 'random_sums'. (4 pts)

In [ ]:
randArray = # YOUR CODE HERE
random_sums = []
# YOUR CODE HERE
print(random_sums)

___

### Sets

In [ ]:
arr1 = np.array([x for x in range(0,50) if x%5 > 2])
arr2 = np.array([x for x in range(0,50) if x%7 > 3])

print('array 1:', arr1)
print('array 2:', arr2)

array 1: [ 3  4  8  9 13 14 18 19 23 24 28 29 33 34 38 39 43 44 48 49]
array 2: [ 4  5  6 11 12 13 18 19 20 25 26 27 32 33 34 39 40 41 46 47 48]


In [ ]:
union = np.union1d(arr1, arr2) #in either arr1 or arr2
print('union:', union)

union: [ 3  4  5  6  8  9 11 12 13 14 18 19 20 23 24 25 26 27 28 29 32 33 34 38
 39 40 41 43 44 46 47 48 49]


In [ ]:
intersect = np.intersect1d(arr1, arr2) #in both arr1 and arr2
print('intersect:', intersect)

intersect: [ 4 13 18 19 33 34 39 48]


### Reshaping

In [ ]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr1.reshape(2, -1) #first number is the number of rows, -1 automatically selects the number that works

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
np.transpose(arr1) #switches the axis

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

____

## Problem 3: Determine the numbers that can be found in  'multiples_15' and and also 'random_sums' (the number appears in both arrays) and put them in an array called 'both' (2 pts)

In [ ]:
# YOUR CODE HERE - The most common solution would have just 1 line!
print(both)

### Sizing an **array**

In [ ]:
arr1 = np.array([1,2,3,4,5,6,7])
print(np.size(arr1))

arr2 = np.array([[3,4,5],[2,4,6]]) #this will count each element within sub-arrays as well
print(np.size(arr2))

7
6


### Sorting an array

In [ ]:
# You can sort an array in multiple ways. For example, sorting an array alphabetically:

arr = np.array(['bob', 'david', 'chen', 'joseph'])
print(np.sort(arr))

# Sorting a 2D array of ints will sort both sub-arrays
arr = np.array([[23,76,14], [90,3,56]])
print(np.sort(arr))

['bob' 'chen' 'david' 'joseph']
[[14 23 76]
 [ 3 56 90]]


## Problem 4: Print the size of the array you found in Problem 3 above. Then, print the sorted array. (1 pt.)





In [ ]:
# YOUR CODE HERE -- Use only 2 lines of code!

<b>Final Note</b>: We know that you might not have any experience in Python or Computer Science/Math in general, and that's completely fine. Don't be intimidated - this is a part of the process! Please come to office hours, and one of the instructors would give you a crash course. Additionally, we have a recording of a Python workshop on our website so that you can use to bridge the gap, if any. If you still feel underprepared, please come talk to one of the instructors - we will work it out.